name: LordWorld
version: 1.0.0
main: br.com.israel.LordWorld
api-version: "26.1.2"
author: Israel

depend:
  - Multiverse-Core

softdepend:
  - FastAsyncWorldEdit

commands:
  lw:
    description: LordWorld main command
    usage: /lw
    permission: lordworld.command

  ping:
    description: Teste do plugin
